# Generated by Django 5.0.8 on 2024-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados unidos'), ('BRAZIL', 'Brasil'), ('CANADA', 'Canada')], max_length=50, null=True)),
            ],
        ),
    ]
